version: '2'  
services:
  nginx:
    image: nginx:latest
    container_name: nginx_page
    ports:
      - "8002:8000"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./assets:/static
    depends_on:
      - web_page
  web:
    build: .
    container_name: web_page
    command: bash -c 'gunicorn ads.wsgi -b 0.0.0.0:8000'
    ports:
       - "82:8002"
    depends_on:
      - db
    volumes:
      - ./assets:/static
    expose:
      - "82"
