version: '2'  
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./assets:/static
    depends_on:
      - web
  web:
    build: .
    container_name: web
    command: bash -c 'gunicorn ads.wsgi -b 0.0.0.0:8001'
    ports:
       - "80:8001"
    depends_on:
      - db
    volumes:
      - ./assets:/static
    expose:
      - "80"
